In [1]:
import numpy as np 
a=np.array([1,2,3])
b=[4,5,6,7]
print(a)
print(a.shape)
print(b)
print(type(b))
print(type(a))
print(a[0],a[1],a[2])
a[0] = 5
print(a)

[1 2 3]
(3,)
[4, 5, 6, 7]
<class 'list'>
<class 'numpy.ndarray'>
1 2 3
[5 2 3]


In [2]:
b=np.array([[1,2,3],[4,5,6]])
print(b.shape)
print(b[0,0] , b[1,0] , b[0,1])

(2, 3)
1 4 2


In [3]:
a=np.zeros((2,2))
print(a)

[[0. 0.]
 [0. 0.]]


In [4]:
a=np.ones((1,2))
print(a)

[[1. 1.]]


In [5]:
c=np.full((2,2),7)
print(c)

[[7 7]
 [7 7]]


In [6]:
#create a 2*2 identity matrix
d=np.eye(2)
print(d)

[[1. 0.]
 [0. 1.]]


In [7]:
# Create an array with random values
e=np.random.random((2,2))
print(e)

[[0.18030931 0.46643909]
 [0.3766537  0.74042499]]


In [8]:
e=np.random.randint((2,2))
print(e)

[0 0]


In [9]:
print(np.linspace(0,5,10))


[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


In [10]:
import array as arr
np.linspace(2.0,3.0,num=5)

np.linspace(2.0,3.0,num=5,endpoint=False)

np.linspace(2.0,3.0,num=5,endpoint=True)


array([2.  , 2.25, 2.5 , 2.75, 3.  ])

In [11]:
b=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(b[:,:])
print(b[:2,1:3])
print(b[0:2,1:2])
print(b[2:3,0:2])
print(b[:2,1:])
print(b[-2:-1,-2:-1])
print(b[-2:1,1:3])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[2 3]
 [6 7]]
[[2]
 [6]]
[[ 9 10]]
[[2 3 4]
 [6 7 8]]
[[7]]
[]


In [12]:
b=np.array([[1,2],[3,4],[5,6]])
print(b[[0,1,2],[0,1,0]])
print(b[0,0] , b[1,1] , b[2,0])
print(b[0,0] , b[1,1])

[1 4 5]
1 4 5
1 4


In [13]:
a = np.array([[1, 2, 3, 4], 
              [5, 6, 7, 8], 
              [9, 10, 11, 12]])

# Define array 'b'
b = np.array([0, 2, 0])

print(a[np.arange(3), b])
a[np.arange(3),b]+=10
print(a)

[1 7 9]
[[11  2  3  4]
 [ 5  6 17  8]
 [19 10 11 12]]


In [14]:
b=np.array([[1,2],[3,4],[5,6]])
bool_idx = (b>2)
print(bool_idx)

[[False False]
 [ True  True]
 [ True  True]]


In [34]:
arr=np.arange(16)
print(arr)
a=arr.reshape(2,8)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]]
